version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
  client:
    build:
      context: client
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - api
volumes:
  mongodb:
